### ISSUE TITLE
`calabash run` should not expect there to be an 'android' or 'ios' profile

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#209]
I ran into this output:

```
$ be calabash run ../../spec/resources/android/xtc-android-sample.apk 
Could not find profile: 'android'

Defined profiles in cucumber.yml:
  * app
  * default
  * formatter
  * verbose
```

This is not a x-platform project.

Do I need to update my support/env.rb and support/hooks.rb?  They were generated some time ago.

**Comment by TobiasRoikjer** [comment]
Yes this is expected behaviour. calabash run uses the profile `android` or `ios`

**Comment by jmoody** [comment]
This doesn't seem right.  If the project is not x-platform, android or ios does not make sense.

Does `calabash generate` allow you to configure this?

**Comment by TobiasRoikjer** [comment]
@jmoody I consider this expected behaviour and not a bug. Have you changed your opinion?

**Comment by jmoody** [comment]
I don't think this is the correct behavior.  Assigning to Karl for a decision.

**Comment by krukow** [comment]
I need more information to decide this. Let's discuss offline.

**Comment by krukow** [comment]
@jmoody @TobiasRoikjer ^

**Comment by TobiasRoikjer** [comment]
@jmoody If you generate skeletons using a newer version this is expected behaviour. You are right that this might be unexpected when you are targeting only one platform, but that means you have created your own hooks and env instead of basing them on the default generated ones.

A user can always just run using `cucumber`.

I am not certain this is the best approach, and I can be convinced to change this behaviour

**Comment by krukow** [comment]
@jmoody  @TobiasRoikjer I don't think we should require profiles of specific names. What we should require is that certain configuration is called so that either iOS or Android is configured - does that make sense.

**Comment by TobiasRoikjer** [comment]
The run command is removed.
